# I tried this but eventually used the more recent fluentd version
# fluentd/Dockerfile
# https://github.com/digikin/fluentd-elastic-kibana/blob/master/fluentd/Dockerfile
#FROM fluent/fluentd:v1.12.0-debian-1.0
#USER root
#RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "5.0.3"]
#COPY fluentd/fluent.conf /fluentd/etc
#USER fluent

FROM fluent/fluentd:v1.14-1

USER root

RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "5.1.4"]

# couldn't manage to mount bind file correctly so I'm packaging it :(
COPY fluentd/fluent.conf /fluentd/etc

# debug
# RUN cat /fluentd/etc/fluent.conf
# CMD ["ls", "-lah", "/fluentd/etc"]
